In [9]:
"""
Complete the following short Mathematics tasks
1. Write a NumPy program to add, subtract, multiply, divide arguments elementwise.
2. Write a NumPy program to round elements of the array to the nearest integer.
3. Write a NumPy program to get true division of the element-wise array inputs.
"""
#1. Write a NumPy program to add, subtract, multiply, divide arguments elementwise.
import numpy as np
arr1  = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8 , 9, 10])
print("Array 1:", arr1)
print("Array 2:", arr2)

arradd = np.add(arr1, arr2) #'add' sums elements of two arrays and puts results in new array
print("Add:", arradd)

arrsub = np.subtract(arr1, arr2) #'subtract' subtracts elements of one array from another array and puts results in new array
print("Subtract:", arrsub)

arrmult = np.multiply(arr1, arr2) #'multiply' multiplies elements of two arrays and puts results in new array
print("Multiply:", arrmult)

arrdiv = np.divide(arr1, arr2) #'divide' divides elements of one array from another array and puts results in new array
print("Divide:", arrdiv)

arrsum = np.sum([arr1, arr2]) #'sum' sums elements of two arrays and returns single number 
print("Sum:", arrsum)


Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Add: [ 7  9 11 13 15]
Subtract: [-5 -5 -5 -5 -5]
Multiply: [ 6 14 24 36 50]
Divide: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Sum: 55


In [11]:
#2. Write a NumPy program to round elements of the array to the nearest integer.
import numpy as np
arr  = np.array([1.23, 2.01, 3.67, 4.89, 5.96])
arr2 = np.around(arr, 0)
print(arr2)

[1. 2. 4. 5. 6.]


In [13]:
#3. Write a NumPy program to get true division of the element-wise array inputs.
import numpy as np
arr1  = np.array([10, 20, 30, 40, 50])
arr2 = np.array([2, 3, 4, 5, 10])

arrtd = np.true_divide(arr1, arr2) #calls same function as 'divide', therefore returns same result
print("True divide:", arrtd) 

arrdiv = np.divide(arr1, arr2) 
print("Divide:", arrdiv)

True divide: [5.         6.66666667 7.5        8.         5.        ]
Divide: [5.         6.66666667 7.5        8.         5.        ]


In [31]:
"""
Extension:
1. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.
2. Write a NumPy program to create a random array with 1000 elements and compute the average, variance,
standard deviation of the array elements.
3. Write a NumPy program to calculate round, floor, ceiling, truncated and round (to the given number of 
decimals) of the input, elementwise of a given array.
4. Write a Python program to find the maximum and minimum value of 1D array.
"""
#1. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product.
import numpy as np
arr1 = np.array([[6, 9, 5], [4, 3, 1], [12, 15, 90], [23, 53, 2], [8, 32, 42]])
arr2 = np.array([[2, 3], [5, 1], [9, 13]])
arrx = np.dot(arr1, arr2) #'dot' returns dot product
print("Array 1:")
print(arr1)
print("Array 2:")
print(arr2)
print("Dot product:")
print(arrx)

Array 1:
[[ 6  9  5]
 [ 4  3  1]
 [12 15 90]
 [23 53  2]
 [ 8 32 42]]
Array 2:
[[ 2  3]
 [ 5  1]
 [ 9 13]]
Dot product:
[[ 102   92]
 [  32   28]
 [ 909 1221]
 [ 329  148]
 [ 554  602]]


In [33]:
"""
2. Write a NumPy program to create a random array with 1000 elements and compute the average, variance,
standard deviation of the array elements.
"""
import numpy as np
arr = np.random.random((100, 10))
x = np.average(arr)
y = np.var(arr)
z = np.std(arr)
print("Average:", x)
print("Variance:", y)
print("Standard deviation:", z)

Average: 0.5068951434511735
Variance: 0.08425752747228757
Standard deviation: 0.29027147202625264


In [35]:
"""
3. Write a NumPy program to calculate round, floor, ceiling, truncated and round (to the given number of 
decimals) of the input, elementwise of a given array.
"""
import numpy as np
arr = np.random.random((3, 3))
a = np.round(arr)
b = np.floor(arr)
c = np.ceil(arr)
d = np.trunc(arr)
e = np.around(arr, 2)
print("Array:")
print(arr)
print("Round:")
print(a)
print("Floor:")
print(b)
print("Ceiling:")
print(c)
print("Truncate:")
print(d)
print("Round to 2 d.p:")
print(e)

Array:
[[0.52623951 0.77219164 0.13817612]
 [0.73131044 0.45577661 0.18669448]
 [0.84820533 0.26478517 0.24431499]]
Round:
[[1. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Floor:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ceiling:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Truncate:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Round to 2 d.p:
[[0.53 0.77 0.14]
 [0.73 0.46 0.19]
 [0.85 0.26 0.24]]


In [42]:
#4. Write a Python program to find the maximum and minimum value of 1D array.
import numpy as np
arr = np.random.random(5)
x = np.max(arr)
y = np.min(arr)

print("Array:")
print(arr)
print("Maximum:")
print(x)
print("Minimum:")
print(y)

Array:
[0.86838597 0.95847189 0.2014718  0.7691289  0.99580483]
Maximum:
0.9958048291089896
Minimum:
0.20147179504825874
