In [2]:
"""
Complete the following short fundamental NumPy tasks.
1. Create a 1d array of numbers from 0 to 9.
2. Convert a 1d array to a 2d array with 2 rows.
3. Write a NumPy program to create an array of the integers from 30 to 70.
4. Write a NumPy program to append values to the end of an array.
"""
#1. Create a 1d array of numbers from 0 to 9.
import numpy as np #Imports NumPy so it can be used using 'np' alias.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) #'np.array' to create array, one set of square brackets for 1d array.
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#2. Convert a 1d array to a 2d array with 2 rows.
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
newarr = arr.reshape(2, 5) #'arr.reshape' converts 'arr' to 2d array (2 integers in brackets) with 2 arrays of 5 elements each (2, 5).
print(newarr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
#3. Write a NumPy Program to create an array of the integers from 30 to 70.
import numpy as np
arr = np.arange(30, 71) #'arange' returns values between given integers, including first int but excluding second
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [27]:
#4. Write a NumPy program to append values to the end of an array.
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
arr = np.append(arr, [10, 11, 12]) #'append' adds values to end of array
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [52]:
"""
Extension
1. Write a NumPy program to find
the number of rows and columns of
a given matrix.
2. Write a NumPy program to create
an array of all the even integers
from 30 to 70.
3. Write a NumPy program to
convert a list and tuple into arrays.
4. Write a NumPy program to
create a structured array from
given student name, height, class
and their data types.

data type = [('name, 'S15'), ('class,
int), ('height, float)]
students_details = [('James, 5, 48.5),
('Nail, 6, 52.5), ( 'Paul', 5, 42.10), (Pit,
5, 40.11)]

Now sort the array on height
"""
#1. Write a NumPy program to find the number of rows and columns of a given matrix.
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print("array:")
print(arr)
print("(rows, columns):", arr.shape) #'shape' returns number of elements in each dimension.


array:
[[1 2 3]
 [4 5 6]]
(rows, columns): (2, 3)


In [50]:
#2. Write a NumPy program to create an array of all the even integers from 30 to 70.
import numpy as np
arr = np.arange(30, 71)
for x in np.nditer(arr[::2]): #'nditer' iterates every element in (arr), [::2] skips one element.
    print(x)

30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70


In [56]:
#3. Write a NumPy program to convert a list and tuple into arrays.
import numpy as np
list_x = [1, 2, 3] #list
tuple_y = (4, 5, 6) #tuple

print(list_x)
print(type(list_x)) #prints data type
print(tuple_y)
print(type(tuple_y))

conv_list = np.array(list_x) #converts to array
conv_tuple = np.array(tuple_y)

print(conv_list)
print(type(conv_list)) 
print(conv_tuple)
print(type(conv_tuple))

[1, 2, 3]
<class 'list'>
(4, 5, 6)
<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>
[4 5 6]
<class 'numpy.ndarray'>


In [79]:
"""
4. Write a NumPy program to
create a structured array from
given student name, height, class
and their data types.

data type = [('name, 'S15'), ('class,
int), ('height, float)]
students_details = [('James, 5, 48.5),
('Nail, 6, 52.5), ( 'Paul', 5, 42.10), (Pit,
5, 40.11)]

Now sort the array on height
"""
import numpy as np
arr = np.array([['Name(s15)', 'Class(int)', 'Height(float)'], ['James', int(5), float(48.5)], ['Nail', int(6), float(52.5)], 
['Paul', int(5), float(42.1)], ['Pit', int(5), float(40.11)]], dtype='<U15') #'dtype' sets max string length to 15
print('String max length:', arr.dtype) #Print string max length
arrh = arr[arr[:, 2].argsort()] #Print array sorted by height[2] (low to high)
print(arrh)

String max length: <U15
[['Pit' '5' '40.11']
 ['Paul' '5' '42.1']
 ['James' '5' '48.5']
 ['Nail' '6' '52.5']
 ['Name(s15)' 'Class(int)' 'Height(float)']]
